
//A factory function for generating workout objects
const workoutGenerator = (dayName, majorLifts, minorLifts) => {
    return {
        dayName: dayName,
        majorLifts: majorLifts,
        minorLifts: minorLifts,
        getRandomMajor() {
            return this.majorLifts[Math.floor(Math.random() * majorLifts.length)]
        },
        getRandomMinor() {
            return this.minorLifts[Math.floor(Math.random() * minorLifts.length)]
        }
    }
}

//Stores the names of the days of the week
const daysOfTheWeek = {
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday', 
    7: 'Sunday'
}

//Store the workouts--generated by the factory function--according to the day.
const daysOfProgram = {
    'Monday': workoutGenerator('Chest', ['Bench Press', 'Incline Bench Press', 'Weighted Dips', 'Decline Bench Press'],
    ['Flyes', 'Pullovers', 'Pushups', 'Pushups', 'Tricep Extensions', 'Dumbell Bench Press']),
    'Tuesday': workoutGenerator('Back', ['Weighted Pullups', 'Bent Over Barbell Rows', 'T-Bar Rows', 'Deadlifts'],
    ['Lat Pulldowns', 'Pullups', 'Alternating Curls', 'Hammer Curls']),
    'Wednesday': 'Rest',
    'Thursday': workoutGenerator('Legs', ['Squat', 'Leg Press', 'Front Squat', 'Weighted Lunges'],
    ['Romanian Deadlifts', 'Leg Extensions', 'Leg Curls', 'Calf Raises']),
    'Friday': workoutGenerator('Shoulders', ['Pike Press', 'Shoulder Press', 'Arnold Press', 'Dumbell Shoulder Press'], 
    ['Lateral Raises', 'Band Shoulder Work', 'Cable Shoulder Press', 'Reverse Flyes']),
    'Saturday': 'Rest',
    'Sunday': 'Rest'
}

//Store the set/rep protocols in variables for easier interpolation later
const reps = {
    1: '3 sets of 5 reps',
    2: '4 sets of 8 reps',
    3: '3 sets of 12 reps'
}

//Randomly determine the day
let day = daysOfTheWeek[Math.ceil(Math.random() * 7)];

//Create workout variable for easier access later.
let workout = daysOfProgram[day];

//Create empty objects as containers for the randomized workouts that will occur on that day.
let majors = {

}
let minors = {
    
}

//Print Day
console.log(`\nGood Morning! It's ${day}!`);

//If rest day, print rest message.
//If a workout day, generate random major and minor exercises, ensuring no duplicates, then print message using interpolation.
if (workout === 'Rest') {
    console.log('Today is a rest day. Take the day off, and try not to work too hard. Let your body rebuild and come back stronger!\n\n');
} else {
    majors[1] = workout.getRandomMajor();
    do {
        majors[2] = workout.getRandomMajor();
    } while (majors[1] === majors[2]);

    minors[1] = workout.getRandomMinor();
    do {
        minors[2] = workout.getRandomMinor();
    } while (minors[1] === minors[2]);
    console.log(`Today is ${workout.dayName} day! Today you will perform:\n\n\t${reps[1]} of ${majors[1]}\n\t${reps[2]} of ${majors[2]}\n\t${reps[3]} of ${minors[1]}\n\t${reps[3]} of ${minors[2]}\n\n`);
};
